name: Welcome New Issues

on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add welcome comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Thanks for opening this issue!
            
             A maintainer will review it soon. Please make sure you've provided all necessary details.